# .github/workflows/main.yml

name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Call the composite action defined in my-action.yml
      - uses: ./.github/workflows/setup.yml@migrate_ci