# .github/workflows/main.yml

name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: fatcat-z/tensorflow-onnx
          ref: migrate_ci

      - name: Check folder
        run: ls ./.github/workflows/

      # Call the composite action defined in my-action.yml
      - name: Run my action
        uses: ./.github/workflows/setup-common

      # Call the composite action defined in my-action.yml
      - name: Run my action yml
        uses: ./.github/workflows/setup.yml