name: setup-common

on:
  push:
    branches:
      - main
  workflow_call:
    inputs:
      tf_version:
        description: 'TensorFlow version'
        required: true
        default: '2.14.0'
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          # pip install pytest pytest-cov pytest-runner coverage graphviz requests pyyaml pillow pandas parameterized sympy coloredlogs flatbuffers timeout-decorator
          pip install numpy

          pip install onnxruntime-extensions
          pip install "tensorflow-text<=${{ inputs.tf_version }}"

          pip uninstall -y tensorflow
          pip install tensorflow==${{ inputs.tf_version }}
          pip uninstall -y protobuf
          pip install "protobuf~=3.20"

          ls /home/runner/work/tensorflow-onnx/tensorflow-onnx/
          ls /home/runner/work/tensorflow-onnx/
          python setup.py install

          pip freeze --all

      - name: Fix Paths (Windows only)
        if: runner.os == 'Windows'
        run: |
          $site_dir = python -c "import site; print(site.getsitepackages()[1])"
          echo "##vso[task.prependpath]$site_dir\numpy\.libs"
          $base_dir = python -c "import site; print(site.getsitepackages()[0])"
          echo "##vso[task.prependpath]$base_dir/Library/bin"

      - name: Display Environment Variables
        run: env
